permalink: /:year:month:day/:title

remote_theme: sammaya164/windows-95-sp1
lang: ja

url: # https://www.example.com
baseurl: /skyblue

# Variables
title: "空色と水色"
google_verification: null

# File management
include:
 - .htaccess
exclude:
 - README.md
 - LICENSE

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

#Plugins
plugins:
  - jemoji

# Header
header:
  links:
    - title: <u>A</u>bout
      url: about.html
    - title: <u>G</u>itHub
      url: http://github.com/sammaya164/skyblue
    # - title: <u>T</u>witter
    #   url: http://twitter.com/
    # - title: <u>S</u>oundcloud
    #   url: http://soundcloud.com/

# In memo_window
enable_markdown: true

