permalink: /:year:month:day/:title

remote_theme: sammaya164/windows-95-sp1
lang: ja

url: # https://www.example.com
baseurl: /skyblue

# variables
title: "空色"
google_verification: null

# File management
include:
 - .htaccess
 - _pages
exclude:
 - README.md
 - LICENSE

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

# Header
header:
  - title: <u>A</u>bout
    url: about.html
  - title: <u>G</u>itHub
    url: http://github.com/sammaya164/skyblue
  # - title: <u>T</u>witter
  #   url: http://twitter.com/
  # - title: <u>S</u>oundcloud
  #   url: http://soundcloud.com/

# Tag list
taglist:
  - name: 'テスト'
    link: tag1
  - name: 'テスト2'
    link: tag2

